name: flutter_qr_scan
description: QR code (scan QRCode and picture) recognition, forked from hetian9288/flutter_qr_reader
version: 1.0.7
homepage: https://github.com/polkawallet-io/flutter_qr_reader
module:
  androidX: true

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: "3.35.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0

flutter:
  plugin:
    platforms:
      android:
        package: me.hetian.flutter_qr_reader
        pluginClass: FlutterQrReaderPlugin
      ios:
        pluginClass: FlutterQrReaderPlugin

  assets:
    - assets/tool_img.png
    - assets/tool_qrcode.png
    - assets/tool_flashlight_close.png
    - assets/tool_flashlight_open.png
