name: Code Quality

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  FLUTTER_VERSION: "3.35.0"
  EXAMPLE_DIRECTORY: example_app

jobs:
  fmt_analyze:
    name: Fmt and Analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: "stable"

      - run: flutter doctor

      - name: Get dependencies
        run: flutter pub get

      - name: Get example app dependencies
        run: flutter pub get
        working-directory: ${{ env.EXAMPLE_DIRECTORY }}

      - name: "Check fmt"
        run: dart format . --line-length 120 --set-exit-if-changed

      - name: "Analyze Code"
        run: flutter analyze  --fatal-warnings
